name: Build and Run C++

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y g++

    - name: Compile the code
      run: g++ -o TicTacToe Xcircle.cpp

    - name: Run the program
      run: ./TicTacToe
