name: Build and Run C++

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: choco install mingw

    - name: Compile the code
      run: g++ -o TicTacToe Xcircle/Xcircle.cpp


    - name: Run the program
      run: TicTacToe.exe
